version: '3'

services:
    db:
      image: mysql:5.7
      container_name: mysqldb2   
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 3307:3306
      restart: always
 
    customerservice:                       
      image: linksport              
      container_name: linksport-app
      ports:
        - "8080:8080"                     
      restart: always
        
      depends_on:                          
        - db                                
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb2:3307/linksport
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root